version: '3'
services:
  database:
    image: "mysql:5.7"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./Config/Database:/docker-entrypoint-initdb.d"
    networks:
      time_arrow_net:
        ipv4_address: 192.168.0.2
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-p"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "none"

  user:
    build: UserService
    volumes:
      - "./Config/User/user-ENV.json:/usr/app/Config/ENV.json"
      - "./Config/User/user-ormconfig.json:/usr/app/ormconfig.json"
    ports:
     - "81:3000"
    depends_on:
      - database
    links:
      - database
    networks:
      time_arrow_net:
        ipv4_address: 192.168.0.3

  topic:
    build: TopicService
    volumes:
      - "./Config/Topic/topic-ENV.json:/usr/app/Config/ENV.json"
      - "./Config/Topic/topic-ormconfig.json:/usr/app/ormconfig.json"
    ports:
      - "86:3000"
    depends_on:
      - database
    links:
      - database
    networks:
      time_arrow_net:
        ipv4_address: 192.168.0.8


networks:
  time_arrow_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24

